### ISSUE TITLE
[CRITICAL PROBLEM]: Cannot connect to server from a CompuServe client

### ISSUE THREAD

**Issue by xproot** [CompuServeReloaded/csr-server#1]
I ran the server and it immediately exited, assuming it had gone into the background, I ran CompuServe, and it wasn't able to connect. Assuming it was in a non-standard port, I tried every localhost port, but it was unable to connect to anything.

**Comment by ghost** [comment]
The server is in its very preliminary stages. It does not open up a TCP socket yet and does not even have the protocol set up yet. Stay tuned for future updates.

**Comment by xproot** [comment]
> The server is in its very preliminary stages. It does not open up a TCP socket yet and does not even have the protocol set up yet. Stay tuned for future updates.

This doesn't make this issue any less valid, in fact, it reinforces this issue. Closing this issue may prevent other folk from knowing about this issue immediately.

**Comment by ghost** [comment]
Can you not post troll comments :norton:

**Comment by xproot** [comment]
This is still an issue.

**Comment by xproot** [comment]
Closing this as completed is INCORRECT.

**Comment by xproot** [comment]
It has been ≈1.5 years since this was reported, and the issue has still not been solved.

**Comment by ghost** [comment]
fuck you

**Comment by xproot** [comment]
> fuck you

This is unprofessional.

> [subpurple](https://github.com/subpurple) closed this as [completed](https://github.com/CompuServeReloaded/csr-server/issues?q=is%3Aissue%20state%3Aclosed%20archived%3Afalse%20reason%3Acompleted) 14 minutes ago

You have changed the reason from __not planned__ to __completed__, which is *incorrect*.
